name: RL3DPToolpathPlanner
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - networkx
  - scipy
  - tqdm
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pip
  - pip:
      - libigl